// ── KeyRef Pro — shared style factory ────────────────────────────────────────
// All theme-flipping colors are CSS variables (defined in src/index.css). The
// `isMobile` flag is the one bit of dynamic state that's awkward in pure CSS
// (we'd need a sub-600 px media-query branch on every rule), so we leave that
// in JS. Components destructure only the styles they need.
//
// To re-skin the app, edit src/index.css. To restructure a layout, edit the
// component. That's the split.

export function makeStyles(isMobile) {
  return {
    // ── App shell ─────────────────────────────────────────────────────────
    app: {
      background: 'var(--bg)',
      minHeight: '100vh',
      fontFamily: "'IBM Plex Sans', sans-serif",
      color: 'var(--text)',
      padding: '0 16px 60px',
    },
    inner: { maxWidth: 1000, margin: '0 auto' },

    // ── Header ────────────────────────────────────────────────────────────
    header: {
      padding: '24px 0 18px',
      borderBottom: '1px solid var(--border)',
      marginBottom: 24,
      display: 'flex',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      flexWrap: 'wrap',
      gap: 12,
    },
    logo: {
      fontFamily: "'Bebas Neue', sans-serif",
      fontSize: isMobile ? 36 : 46,
      letterSpacing: 2,
      lineHeight: 1,
      color: 'var(--logo)',
    },
    logoSub: {
      fontFamily: 'monospace',
      fontSize: 9,
      color: '#787878',
      letterSpacing: 3,
      marginTop: 3,
    },
    headerRight: { display: 'flex', alignItems: 'center', gap: 8 },
    statusBadge: (online) => ({
      fontFamily: 'monospace',
      fontSize: 9,
      letterSpacing: 1,
      padding: '4px 8px',
      border: `1px solid ${online ? 'var(--ok)' : 'var(--warn)'}`,
      color: online ? 'var(--ok)' : 'var(--warn)',
      textTransform: 'uppercase',
    }),
    themeToggle: {
      background: 'transparent',
      border: '1px solid var(--border)',
      color: 'var(--text)',
      fontSize: 16,
      padding: '7px 10px',
      cursor: 'pointer',
      fontFamily: 'monospace',
    },

    // ── Panels ────────────────────────────────────────────────────────────
    panel: {
      background: 'var(--panel)',
      border: '1px solid var(--border)',
      padding: 20,
      marginBottom: 16,
    },
    panelLabel: {
      fontFamily: 'monospace',
      fontSize: 10,
      letterSpacing: 3,
      color: 'var(--accent)',
      textTransform: 'uppercase',
      marginBottom: 16,
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    panelLabelHint: {
      fontFamily: 'monospace',
      fontSize: 9,
      color: 'var(--mute)',
      letterSpacing: 1,
      textTransform: 'none',
      marginLeft: 'auto',
    },
    labelBar: { width: 12, height: 2, background: 'var(--accent)', display: 'block' },

    // ── Mode toggle ───────────────────────────────────────────────────────
    // Segmented-control structure: a relative wrapper containing one
    // absolutely-positioned indicator pill plus the buttons. The pill's
    // `left` and `width` are set by ModeToggle.jsx based on each button's
    // measured offsetLeft/offsetWidth, and CSS transitions handle the slide.
    modeToggle: {
      display: 'flex',
      position: 'relative',
      marginBottom: 16,
      background: 'var(--panel)',
      border: '1px solid var(--border)',
      padding: 4,
      gap: 4,
    },
    modeToggleIndicator: {
      position: 'absolute',
      top: 4,
      bottom: 4,
      background: 'var(--accent)',
      transition: 'left 240ms cubic-bezier(0.4, 0, 0.2, 1), width 240ms cubic-bezier(0.4, 0, 0.2, 1), opacity 200ms ease',
      pointerEvents: 'none',
      zIndex: 0,
    },
    modeBtn: (active) => ({
      flex: 1,
      minWidth: 0,
      background: 'transparent',
      border: 'none',
      color: active ? '#000' : 'var(--text)',
      fontFamily: 'monospace',
      fontSize: 11,
      letterSpacing: 2,
      padding: '10px 12px',
      textTransform: 'uppercase',
      cursor: 'pointer',
      fontWeight: active ? 600 : 400,
      position: 'relative',
      zIndex: 1,
    }),

    // ── Form fields ───────────────────────────────────────────────────────
    formRow: {
      display: 'grid',
      gridTemplateColumns: isMobile ? '1fr' : '90px 1fr 1fr',
      gap: 10,
      marginBottom: 12,
    },
    field: { display: 'flex', flexDirection: 'column', gap: 5 },
    fieldLabel: {
      fontFamily: 'monospace',
      fontSize: 9,
      letterSpacing: 2,
      color: 'var(--mute)',
      textTransform: 'uppercase',
    },
    selWrap: { position: 'relative' },
    select: {
      background: 'var(--input)',
      border: '1px solid var(--border-strong)',
      color: 'var(--text)',
      fontFamily: 'monospace',
      fontSize: 13,
      padding: '9px 28px 9px 10px',
      width: '100%',
      appearance: 'none',
      WebkitAppearance: 'none',
      outline: 'none',
    },
    selArrow: {
      position: 'absolute',
      right: 10,
      top: '50%',
      transform: 'translateY(-50%)',
      color: 'var(--accent)',
      fontSize: 11,
      pointerEvents: 'none',
    },
    inputNum: {
      background: 'var(--input)',
      border: '1px solid var(--border-strong)',
      color: 'var(--text)',
      fontFamily: 'monospace',
      fontSize: 13,
      padding: '9px 10px',
      width: '100%',
      outline: 'none',
    },

    // ── VIN row ───────────────────────────────────────────────────────────
    vinRow: { display: 'flex', gap: 8, marginBottom: 12, alignItems: 'stretch' },
    vinInput: {
      flex: 1,
      background: 'var(--input)',
      border: '1px solid var(--border-strong)',
      color: 'var(--text)',
      fontFamily: 'monospace',
      fontSize: 11,
      padding: '8px 10px',
      outline: 'none',
      textTransform: 'uppercase',
    },
    vinBtn: {
      background: 'transparent',
      border: '1px solid var(--accent)',
      color: 'var(--accent)',
      fontFamily: 'monospace',
      fontSize: 10,
      padding: '8px 12px',
      cursor: 'pointer',
      textTransform: 'uppercase',
      letterSpacing: 1,
      whiteSpace: 'nowrap',
    },
    vinFlash: {
      fontFamily: 'monospace',
      fontSize: 11,
      color: 'var(--ok)',
      marginBottom: 12,
      padding: '6px 10px',
      background: 'var(--ok-tint)',
      borderLeft: '2px solid var(--ok)',
    },

    // ── Lookup button + error ─────────────────────────────────────────────
    btnLookup: (disabled) => ({
      width: '100%',
      background: disabled ? '#555' : 'var(--accent)',
      border: 'none',
      color: disabled ? '#999' : '#000',
      fontFamily: "'Bebas Neue', sans-serif",
      fontSize: 20,
      letterSpacing: 3,
      padding: 13,
      cursor: disabled ? 'not-allowed' : 'pointer',
      opacity: disabled ? 0.5 : 1,
      minHeight: 44,
    }),
    errMsg: {
      background: 'var(--err-tint)',
      borderLeft: '3px solid var(--err)',
      color: 'var(--err)',
      fontFamily: 'monospace',
      fontSize: 12,
      padding: '11px 15px',
      marginBottom: 14,
    },

    // ── Result card ───────────────────────────────────────────────────────
    resultCard: {
      background: 'var(--panel)',
      border: '1px solid var(--border)',
      marginBottom: 16,
      overflow: 'hidden',
    },
    resultHeader: {
      background: 'var(--header-bg)',
      borderBottom: '1px solid var(--border)',
      padding: '12px 18px',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    resultVehicle: {
      fontFamily: "'Bebas Neue', sans-serif",
      fontSize: isMobile ? 20 : 24,
      letterSpacing: 1,
      color: 'var(--accent)',
      lineHeight: 1,
    },
    btnSave: (s) => ({
      background: 'transparent',
      border: `1px solid ${s ? 'var(--ok)' : 'var(--border-strong)'}`,
      color: s ? 'var(--ok)' : 'var(--mute)',
      fontFamily: 'monospace',
      fontSize: 10,
      letterSpacing: 2,
      padding: '5px 11px',
      cursor: s ? 'default' : 'pointer',
      textTransform: 'uppercase',
      whiteSpace: 'nowrap',
      minHeight: 44,
    }),
    resultBody: { padding: 18, display: 'grid', gap: 10 },
    dataRow: (isLast) => ({
      display: 'grid',
      gridTemplateColumns: isMobile ? '100px 1fr' : '150px 1fr',
      gap: 10,
      alignItems: 'start',
      borderBottom: isLast ? 'none' : '1px solid var(--border)',
      paddingBottom: isLast ? 0 : 10,
    }),
    dataKey: {
      fontFamily: 'monospace',
      fontSize: 9,
      letterSpacing: 2,
      color: 'var(--mute)',
      textTransform: 'uppercase',
      paddingTop: 2,
    },
    dataVal: {
      fontFamily: 'monospace',
      fontSize: 13,
      color: 'var(--text)',
      lineHeight: 1.5,
      wordBreak: 'break-word',
    },
    dataValHi: {
      fontFamily: 'monospace',
      fontSize: 15,
      color: 'var(--accent)',
      fontWeight: 600,
      lineHeight: 1.5,
    },
    dataValYes: {
      fontFamily: 'monospace',
      fontSize: 13,
      color: 'var(--ok)',
      lineHeight: 1.5,
    },
    dataValMuted: {
      fontFamily: 'monospace',
      fontSize: 13,
      color: 'var(--mute-val)',
      lineHeight: 1.5,
    },
    tag: {
      display: 'inline-block',
      background: 'var(--accent-tint)',
      border: '1px solid var(--accent-rim)',
      color: 'var(--accent)',
      fontFamily: 'monospace',
      fontSize: 12,
      padding: '4px 10px',
      margin: '2px 4px 2px 0',
      cursor: 'pointer',
      userSelect: 'none',
      minHeight: 28,
    },
    notesBox: {
      background: 'var(--notes-bg)',
      borderLeft: '2px solid var(--accent-rim)',
      padding: '9px 13px',
      fontFamily: 'monospace',
      fontSize: 12,
      color: 'var(--mute)',
      lineHeight: 1.6,
    },

    // ── OBP procedure ─────────────────────────────────────────────────────
    obpToggle: {
      background: 'transparent',
      border: '1px solid var(--accent)',
      color: 'var(--accent)',
      fontFamily: 'monospace',
      fontSize: 11,
      padding: '6px 12px',
      cursor: 'pointer',
      textTransform: 'uppercase',
      marginTop: 6,
      letterSpacing: 1,
    },
    obpPanel: {
      background: 'var(--notes-bg)',
      border: '1px solid var(--border)',
      borderLeft: '3px solid var(--accent)',
      padding: 14,
      marginTop: 8,
      fontFamily: 'monospace',
      fontSize: 12,
      color: 'var(--text)',
      lineHeight: 1.6,
    },
    obpTitle: {
      color: 'var(--accent)',
      fontWeight: 600,
      marginBottom: 8,
      textTransform: 'uppercase',
      letterSpacing: 1,
    },

    // ── Saved / recent list rows ──────────────────────────────────────────
    savedList: { display: 'flex', flexDirection: 'column', gap: 7, marginTop: 12 },
    savedItem: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '9px 13px',
      background: 'var(--input)',
      border: '1px solid var(--border)',
      cursor: 'pointer',
      gap: 10,
      flexWrap: isMobile ? 'wrap' : 'nowrap',
    },
    savedVehicle: {
      fontFamily: 'monospace',
      fontSize: 13,
      color: 'var(--text)',
      flex: 1,
      minWidth: 100,
    },
    savedBlank: { fontFamily: 'monospace', fontSize: 11, color: 'var(--accent)' },
    btnDel: {
      background: 'transparent',
      border: 'none',
      color: 'var(--mute)',
      cursor: 'pointer',
      fontSize: 18,
      padding: '0 4px',
      lineHeight: 1,
      minWidth: 28,
      minHeight: 28,
    },
    empty: {
      fontFamily: 'monospace',
      fontSize: 11,
      color: 'var(--mute-val)',
      letterSpacing: 1,
      padding: '6px 0',
    },
    savedSearchInput: {
      background: 'var(--input)',
      border: '1px solid var(--border-strong)',
      color: 'var(--text)',
      fontFamily: 'monospace',
      fontSize: 12,
      padding: '8px 10px',
      width: '100%',
      outline: 'none',
      marginBottom: 8,
    },
    savedNoteInput: {
      background: 'var(--input)',
      border: '1px solid var(--border)',
      color: 'var(--text)',
      fontFamily: 'monospace',
      fontSize: 12,
      padding: '8px 10px',
      width: '100%',
      outline: 'none',
    },
    savedNoteText: {
      fontFamily: 'monospace',
      fontSize: 11,
      color: '#787878',
      marginTop: 4,
    },

    // ── Ignition prompt ───────────────────────────────────────────────────
    ignitionPanel: {
      background: 'var(--accent-tint3)',
      borderLeft: '3px solid var(--accent)',
      color: 'var(--text)',
      fontFamily: 'monospace',
      fontSize: 12,
      padding: '12px 14px',
      marginBottom: 14,
      display: 'grid',
      gap: 8,
    },
    ignitionButton: {
      background: 'transparent',
      border: '1px solid var(--accent)',
      color: 'var(--accent)',
      fontFamily: 'monospace',
      fontSize: 11,
      padding: '8px 12px',
      cursor: 'pointer',
      textTransform: 'uppercase',
      minHeight: 36,
    },

    // ── Universal search ──────────────────────────────────────────────────
    searchInput: {
      background: 'var(--input)',
      border: '1px solid var(--border-strong)',
      color: 'var(--text)',
      fontFamily: 'monospace',
      fontSize: 14,
      padding: '12px 14px',
      width: '100%',
      outline: 'none',
      marginBottom: 10,
    },
    historyPill: {
      background: 'transparent',
      border: '1px solid var(--border)',
      color: 'var(--mute)',
      fontFamily: 'monospace',
      fontSize: 10,
      padding: '4px 10px',
      cursor: 'pointer',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    typeBadge: (type) => {
      const c = {
        model: 'var(--accent)',
        chip: 'var(--ok)',
        obp: '#a78bfa',
        codeRange: '#5fa6e0',
        fuzzy: 'var(--mute)',
      }[type] || 'var(--mute)';
      return {
        fontFamily: 'monospace',
        fontSize: 8,
        letterSpacing: 1,
        padding: '2px 6px',
        border: `1px solid ${c}`,
        color: c,
        textTransform: 'uppercase',
        borderRadius: 2,
      };
    },

    // ── Footer ────────────────────────────────────────────────────────────
    footer: {
      marginTop: 32,
      paddingTop: 14,
      borderTop: '1px solid var(--border)',
      fontFamily: 'monospace',
      fontSize: 9,
      color: 'var(--mute-val)',
      letterSpacing: 2,
      textTransform: 'uppercase',
      textAlign: 'center',
    },
  };
}
